// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as Random from "bs-platform/lib/es6/random.js";

function randomIntRange(min, max) {
  return Random.$$int((max - min | 0) + 1 | 0) + min | 0;
}

function getHanzi() {
  var ordinal = randomIntRange(19968, 40959);
  var text = String.fromCodePoint(ordinal);
  return /* record */[
          /* text */text,
          /* ordinal */ordinal
        ];
}

export {
  randomIntRange ,
  getHanzi ,
  
}
/* No side effect */
