// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as Random from "bs-platform/lib/es6/random.js";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as CoolCharGenerator$ReactTemplate from "./CoolCharGenerator.bs.js";

Random.self_init(/* () */0);

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, CoolCharGenerator$ReactTemplate.make(/* array */[])), "app");

export {
  
}
/*  Not a pure module */
